from objects.tree.tree import Tree


def format_tree_info(tree: Tree) -> list[str]:
    return [
        "объект: дерево",
        f"id: {tree.id}",
        f"тип: {tree.species_id}",
        f"сеть корней: {tree.root_network_id}",
        f"возраст: {tree.age}",
        f"толщина ствола: {tree.trunk_thickness}",
        f"высота: {tree.height}",
        f"веток: {tree.branch_count} / {tree.max_branch_count}",
        f"листьев: {tree.leaf_count} / {tree.max_leaf_count}",
        f"корней позиций: {len(tree.root_positions)}",
        f"активный росток: {tree.has_active_sprout}",
        f"проверка ростка: {tree.sprout_check_interval}",
        f"шанс ростка: {tree.sprout_spawn_chance}",
        f"вода от корней за тик: {tree.last_water_income}",
        f"буфер воды: {round(tree.water_buffer, 5)} / {tree.water_buffer_capacity}",
        f"нужно на жизнь/тик: {tree.maintenance_water_need_per_tick}",
        f"нужно на рост/тик: {tree.growth_water_need_per_tick}",
        f"оплачено жизни: {tree.last_maintenance_paid}",
        f"оплачено роста: {tree.last_growth_paid}",
        f"прогресс роста: {round(tree.growth_progress, 4)}",
        f"здоровье: {round(tree.health, 4)}",
        f"живое: {tree.alive}",
        "",
        f"таймер падения ветки: {round(tree._branch_drop_progress, 3)} / {tree.branch_drop_check_interval}",
        f"таймер роста ветки: {round(tree._branch_regrow_progress, 3)} / {tree.branch_regrow_check_interval}",
        f"таймер падения листа: {round(tree._leaf_drop_progress, 3)} / {tree.leaf_drop_check_interval}",
        f"таймер роста листа: {round(tree._leaf_regrow_progress, 3)} / {tree.leaf_regrow_check_interval}",
        "",
        f"базовый шанс падения ветки: {tree.branch_drop_base_chance}",
        f"итоговый шанс падения ветки: {tree.get_branch_drop_chance()}",
        f"last roll ветки: {tree.last_branch_drop_roll}",
        f"всего выпало веток: {tree.dropped_branches_total}",
        "",
        f"базовый шанс падения листа: {tree.leaf_drop_base_chance}",
        f"итоговый шанс падения листа: {tree.get_leaf_drop_chance()}",
        f"last roll листа: {tree.last_leaf_drop_roll}",
        f"всего выпало листьев: {tree.dropped_leaves_total}",
        "",
        f"последнее событие кроны: {tree.last_canopy_event}",
        "",
        f"рост корня интервал: {tree.root_growth_check_interval}",
        f"рост корня шанс: {tree.root_growth_base_chance}",
        f"базовый шанс роста ветки: {tree.branch_regrow_base_chance}",
        f"итоговый шанс роста ветки: {tree.get_branch_regrow_chance()}",
        f"базовый шанс роста листа: {tree.leaf_regrow_base_chance}",
        f"итоговый шанс роста листа: {tree.get_leaf_regrow_chance()}",
    ]